### ISSUE TITLE
block-grid columns are not collapsing in Gmail app

### ISSUE THREAD

**Issue by RafaelFunchal** [zurb/foundation-emails#118] opened 2015-01-16 17:54 UTC
Hey guys!

First, thank you for all your work. I really like all Zurb tools.

About my issue: I'm creating an email using `block-grid` because it has to be responsive in Gmail app, but the columns are not collapsing.

I'm following the doc:

```html
<table class="container">
  <tr>
    <td>

      <table class="block-grid two-up">
        <tr>
          <td>

            Column #1

          </td><td> <!-- Make sure the tags are directly next to each other -->

            Column #2

          </td>
        </tr>
      </table>

    </td>
  </tr>
</table>
```
and I already inserted the media query:

```CSS
@media only screen and (max-width: 600px) {
  table[class="container"] .block-grid td {
    width: 100% !important;
  }
}
```

Can you help me?

**Comment by lancesells** [comment] 2015-01-30 21:26
This is old but I believe it's still relevant: https://www.campaignmonitor.com/forums/topic/7288/gmail-ios-app-ignores-meda-declaration-in-css/

Gmail apps and gmail itself are pretty behind the times when it comes to rendering emails.

**Comment by brillman00** [comment] 2015-01-30 21:28
If you creative supports it, give this a shot:
https://www.campaignmonitor.com/blog/post/4240/creating-a-centred-responsive-design-without-media-queries

**Comment by rafaelfunchal** [comment] 2015-02-04 08:37
Thanks guys, I'll look at these examples

**Comment by florian-sander** [comment] 2015-03-24 13:58
I also tried getting the block grid to work, but it is not collapsing in the GMail web client, GMail android client or Outlook.

I am a bit confused. The web page explicitly states that the block grid should be used for these otherwise tricky clients. But it does not for me and it seems that other people are having the same issues.

Has anyone ever gotten the block grid to work as advertised, or is the documentation simply wrong and the block grid is also not responsive on GMail/Outlook?

**Comment by raviedavie** [comment] 2015-05-01 09:27
Did anyone get to the bottom of this? I'm having the same issue.

**Comment by urbackmk** [comment] 2015-05-13 19:00
I'm also having the same problem.  The block-grid seems to rely on media queries even though the documentation states otherwise.

**Comment by mdedetrich** [comment] 2015-08-31 09:06
I also confirm the confusion that is caused by this. The language used in the docs implies that `block-grid` should be used when you can't rely on media queries, however that isn't the case.

In fact, Zurb Ink doesn't seem to be able to specify a way to make flexible column layout that isn't using visibility classes

**Comment by tdhartwick** [comment] 2016-05-02 23:31
We're no longer supporting v1, however to clarify what I think was happening was that the block-grid was expected to break to 100% width. Gmail, however, doesn't respect media queries, as @urbackmk mentions. The intention of the block grid was to kind of fake responsiveness since display inline-block works. Basically, things would just stack if the viewport ran out of room.

This is still the current approach in v2. We chose not to use the complicated "ghost tables" that can help achieve a responsive email in gmail. 

We ultimately chose to make a simpler approach that worked on the majority of clients. Again, it's not a perfectly responsive email, but the block-grid does fake it. Going to close this issue for now. Thanks!

**Closed by tdhartwick** 2016-05-02 23:31 UTC
Labels: Ink 1.0

**Comment by york-xtrem** [comment] 2016-10-27 10:31
I've tried this and I still happening :(

Index.html:
[index.zip](https://github.com/zurb/foundation-emails/files/555497/index.zip)

app.scss:
[app.zip](https://github.com/zurb/foundation-emails/files/555499/app.zip)

![photo_2016-10-27_12-26-49](https://cloud.githubusercontent.com/assets/14836838/19763964/d9426dde-9c40-11e6-824f-4a71a3d6713a.jpg)
![photo_2016-10-27_12-26-53](https://cloud.githubusercontent.com/assets/14836838/19763965/d95abfec-9c40-11e6-9a43-00f08a394d9f.jpg)
